portafolio/blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('post-list/', views.post_list, name='post_list'),
    path('<int:post_id>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/add_comment/', views.add_comment, name='add_comment'),
    path('newpost/', views.new_post, name='new_post'),
    path('<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('<int:post_id>/delete/', views.post_delete, name='post_delete'),
    
]

portafolio/delivery/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('newshipment/', views.new_shipment, name='newshipment'),
    path('searchshipment/', views.search_shipment, name='searchshipment'),
    path('myshipments/', views.my_shipments, name='myshipments'),
    path('sendmoney/', views.send_money, name='sendmoney'),
]

portafolio/portafolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('authentication/', include('authentication.urls')),
    path('notes/', include('notes.urls')),
    path('blog/', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portafolio/delivery/models.py
import uuid
from django.db import models

ESTADOS_ENVIOS = (
    ('pendiente', 'Pendiente'),
    ('en_transito', 'En tránsito'),
    ('entregado', 'Entregado'),
    ('devuelto', 'Devuelto'),
    ('cancelado', 'Cancelado'),
)

class Envio(models.Model):
    numero_seguimiento = models.CharField(max_length=50, unique=True, editable=False)
    remitente = models.CharField(max_length=255)
    destinatario = models.CharField(max_length=255, null=False, blank=False)
    fecha_envio = models.DateTimeField(auto_now_add=True)
    direccion_destino = models.CharField(max_length=255, blank=False, null=False)
    valor_declarado = models.IntegerField(blank=False)
    estado = models.CharField(max_length=50, choices=ESTADOS_ENVIOS, default='pendiente')
    # Otros campos según tus necesidades

    def save(self, *args, **kwargs):
        if not self.numero_seguimiento:
            self.numero_seguimiento = str(uuid.uuid4()).replace('-', '').upper()[:12]
        super().save(*args, **kwargs)

    def __str__(self):
        return f'Envío {self.numero_seguimiento}'

class Paquete(models.Model):
    envio = models.ForeignKey(Envio, related_name='paquetes', on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=255)
    peso = models.DecimalField(max_digits=5, decimal_places=2)
    # Otros campos según tus necesidades

class EstadoEnvio(models.Model):
    envio = models.ForeignKey(Envio, related_name='estados', on_delete=models.CASCADE)
    estado = models.CharField(max_length=50, choices=ESTADOS_ENVIOS)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    descripcion = models.TextField()

    def __str__(self):
        return f'Estado {self.estado} de envío {self.envio.numero_seguimiento}'

portafolio/delivery/forms.py
from django import forms
from .models import Envio, Paquete

class PaqueteForm(forms.ModelForm):
    class Meta:
        model = Paquete
        fields = ['descripcion', 'peso']

class EnvioForm(forms.ModelForm):
    destinatario = forms.CharField(label="Destinatario")
    descripcion_paquete = forms.CharField(label="Descripción del paquete")
    peso_paquete = forms.DecimalField(label="Peso del paquete", max_digits=5, decimal_places=2)

    class Meta:
        model = Envio
        exclude = ['numero_seguimiento', 'remitente', 'estado']
        fields = ['destinatario', 'direccion_destino', 'valor_declarado']  # Excluimos 'estado'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.initial['estado'] = 'pendiente'  # Valor inicial de 'estado'

    def save(self, commit=True, user=None):
        instance = super().save(commit=False)
        if user:
            instance.remitente = user.username
        if commit:
            instance.save()

            # Crear y asociar el paquete al envío
            paquete = Paquete(
                envio=instance,
                descripcion=self.cleaned_data['descripcion_paquete'],
                peso=self.cleaned_data['peso_paquete']
            )
            paquete.save()

        return instance

portafolio/delivery/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .models import Envio
from .forms import EnvioForm  # Necesitarás crear un formulario para crear nuevos envíos
from django.contrib.auth.decorators import login_required
from django.contrib import messages

def search_shipment(request):
    # Lógica para buscar un envío por número de seguimiento u otros criterios
    if request.method == 'POST':
        numero_seguimiento = request.POST.get('numero_seguimiento')
        envio = Envio.objects.filter(numero_seguimiento=numero_seguimiento).first()
        if envio:
            return render(request, 'delivery/search_shipment.html', {'envio': envio})
        else:
            error_message = 'Envío no encontrado.'
            return render(request, 'delivery/search_shipment.html', {'error_message': error_message})
    return render(request, 'delivery/search_shipment.html')

@login_required
def new_shipment(request):
    if request.method == 'POST':
        form = EnvioForm(request.POST)
        if form.is_valid():
            envio = form.save(commit=False)
            envio.remitente = request.user
            envio.save()
            messages.success(request, 'Envío creado exitosamente.')
            return redirect('myshipments')
    else:
        form = EnvioForm()

    return render(request, 'delivery/new_shipment.html', {'form': form})


@login_required
def my_shipments(request):
    shipments = Envio.objects.filter(remitente=request.user)
    return render(request, 'delivery/my_shipments.html', {'shipments':shipments})

@login_required
def send_money(request):
    return render(request, 'delivery/money_sending.html')

portafolio/delivery/templates/delivery/money_sending.html
{% extends 'common/base.html' %}

{% block main_content %}
<div class="main-container">
    <div class="icon">🚧</div>
    <h1>¡Oops!</h1>
    <p>Esta página está en construcción. ¡Vuelve pronto para más novedades!</p>
</div>
{% endblock %}

portafolio/delivery/templates/delivery/my_shipments.html
{% extends 'common/base.html' %}

{% block main_content %}
<h1>Mis Envíos</h1>
<div class="main-container">
        {% for shipment in shipments %}
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-4">
                    <div class="card-body">
                        <h5 class="card-title">Envío: {{ shipment.numero_seguimiento }}</h5>
                        <p class="card-text"><strong>Destinatario:</strong> {{ shipment.destinatario }}</p>
                        <p class="card-text"><strong>Dirección Destino:</strong> {{ shipment.direccion_destino }}</p>
                        <p class="card-text"><strong>Valor Declarado:</strong> {{ shipment.valor_declarado }}</p>
                        <p class="card-text"><strong>Estado:</strong> {{ shipment.estado }}</p>
                        <p class="card-text"><strong>Fecha de Envío:</strong> {{ shipment.fecha_envio }}</p>
                    </div>
                </div>
            </div>
        </div>    
        {% endfor %}
</div>
{% endblock %}

portafolio/delivery/templates/delivery/new_shipment.html
<!-- new_shipment.html -->

{% extends 'common/base.html' %}

{% block main_content %}
<div class="container main-container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h2 class="card-title mb-0">Nuevo Envío</h2>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}

                        <div class="text-center mt-3">
                            <button type="submit" class="btn btn-primary">Crear Envío</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

portafolio/delivery/templates/delivery/search_shipment.html
<!-- search_shipment.html -->

{% extends 'common/base.html' %}

{% block main_content %}
<div class="container main-container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h2 class="card-title mb-0">Buscar Envío</h2>
                </div>
                <div class="card-body">
                    <!-- Mostrar mensajes de éxito o error -->
                    {% if error_message %}
                        <div class="alert alert-danger" role="alert">
                            {{ error_message }}
                        </div>
                    {% endif %}

                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="numero_seguimiento" class="form-label">Número de Seguimiento:</label>
                            <input type="text" id="numero_seguimiento" name="numero_seguimiento" class="form-control" required>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Buscar</button>
                        </div>
                    </form>

                    {% if envio %}
                        <div class="mt-3">
                            <h3>Detalles del Envío</h3>
                            <ul class="list-group">
                                <li class="list-group-item"><strong>Número de Seguimiento:</strong> {{ envio.numero_seguimiento }}</li>
                                <li class="list-group-item"><strong>Remitente:</strong> {{ envio.remitente.usuario.username }}</li>
                                <li class="list-group-item"><strong>Destinatario:</strong> {{ envio.destinatario.usuario.username }}</li>
                                <li class="list-group-item"><strong>Dirección de Destino:</strong> {{ envio.direccion_destino }}</li>
                                <li class="list-group-item"><strong>Valor Declarado:</strong> {{ envio.valor_declarado }}</li>
                                <li class="list-group-item"><strong>Estado:</strong> {{ envio.get_estado_display }}</li>
                                <!-- Agrega más detalles del envío según sea necesario -->
                            </ul>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}